### ISSUE TITLE
Black Sky while outside of craft on Kerbin

### ISSUE THREAD

**Issue by Corsair427** [FirstPersonKSP/Kerbal-VR#328]
The Vr works great except when viewing the craft from the outside or while on EVA, The Kerbin sky appears black, the strange thing is if I look straight up through the visor it does appear blue, its almost like a layer issue. Running the latest version of Kerbal with vive pro 2 on Windows 10.

**Comment by JonnyOThan** [comment]
Please review the visual mod install instructions: https://github.com/FirstPersonKSP/Kerbal-VR/wiki/Installation-Guide#5-visual-mods

Since you didn't include a log file, I can't do anything with this.
